version: '3'

volumes:
  trustid-db-data:

networks:
  web:
    external: true

services:
  trustid-postgres:
    image: postgres
    restart: always
    volumes:
      - trustid-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - web
  trustid-nginx:
    image: nginx
    labels:
      - traefik.frontend.rule=Host:api.trustid-project.eu
      - traefik.backend=trustid-nginx
      - traefik.port=80
      - traefik.enable=true
      - traefik.frontend.redirect.entryPoint=https
    container_name: trustid-nginx
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - ./staticfiles:/static
    depends_on:
      - trustid-server
    networks:
      - web
  trustid-server:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py collectstatic --no-input && gunicorn --config=/code/config/gunicorn/config.py trustid_project.wsgi:application"
    container_name: trustid-server
    env_file:
      - ./django_variables.env
    volumes:
      - .:/code
      - ./static/:/static
      - ./media/:/media
      # - ./config/nginx/certs/:/etc/certs
      - ./staticfiles/:/code/staticfiles
    expose:
        - "10000"
    depends_on:
      - trustid-postgres
      - trustid-rabbit
    stdin_open: true
    tty: true
    networks:
      - web
  trustid-rabbit:
    image: "rabbitmq:3-management"
    hostname: "trustid-rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "trustid-rabbit"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
  trustid-celery:
    build: .
    env_file:
      - ./django_variables.env
    working_dir: /code
    command:  ./init_celery.sh
    links:
      - trustid-rabbit
    volumes:
      - .:/code
    networks:
      - web

